backend:
  name: git-gateway
  branch: main # GitHubのデフォルトブランチ

media_folder: "images" # CMSでアップロードする画像の保存先
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
