name: Deploy to WebARENA Server
on:
  push:
    branches:
      - main   # mainブランチにpushされたらデプロイ

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # コードをGitHub Actionsランナーにチェックアウト
      - uses: actions/checkout@v4

      # サーバーにファイルをアップロード
      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./*"           # リポジトリのファイルを全てアップ
          target: "/var/www/html" # Nginxのrootディレクトリ
          overwrite: true         # 上書きする

