name: Deploy to WebARENA Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Upload files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "./*"              # リポジトリ直下の全ファイル
          target: "/var/www/html"    # Nginx root
          overwrite: true
          strip_components: 0
          timeout: 30s               # 秒単位を指定
          # 以下の無効オプションは削除
          # recursive, strict
